server:
  port: 8080
  servlet:
    context-path: /api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/api/feed/**
        - id: likes-service
          uri: lb://like-service
          predicates:
            - Path=/api/likes/**
eureka:
  client:
    service-url:
      defaultZone: "http:localhost:8761/eureka"