server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Optional: Auto-route services by name
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/api/feed/**
        - id: likes-service
          uri: lb://likes-service
          predicates:
            - Path=/api/likes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

app:
  secret-key: "this_is_my_long_secret_key_for_jwt_creation"
  jwt-valid-duration : 3600000
  jwt-issuer: "phumie-api-service"