server:
  port: 8081
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/phumie_project
    username: root
    password: "@ZXCp0001"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # Maximum number of connections in the pool
      minimum-idle: 2 # Minimum number of idle connections
      idle-timeout: 30000 # Time in milliseconds before an idle connection is removed
      max-lifetime: 1800000 # Maximum lifetime of a connection in the pool

  # JPA (Hibernate) configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    cache-names:
      - userIdsCache
      - userDtosCache
      - userEntitiesCache
    caffeine:
      spec: initialCapacity=100,maximumSize=10,expireAfterAccess=400s

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.microservice: DEBUG

app:
  welcome-message: "Welcome to My Microservice!"
  max-retries: 3