server:
  port: 8081
  servlet:
    context-path: /api/posts

spring:
  application:
    name: post-service

  datasource:
    url: jdbc:mysql://localhost:3306/classicmodels
    username: root
    password: "@ZXCp0001"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # Maximum number of connections in the pool
      minimum-idle: 2 # Minimum number of idle connections
      idle-timeout: 30000 # Time in milliseconds before an idle connection is removed
      max-lifetime: 1800000 # Maximum lifetime of a connection in the pool

  # JPA (Hibernate) configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.microservice: DEBUG

app:
  welcome-message: "Welcome to the Posts Service for Phumie"
  max-retries: 3