server:
  port: 8082

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:mysql://localhost:3306/phumie_project
    username: root
    password: "@ZXCp0001"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      key-prefix: "post-service::"
      time-to-live: 300s
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: post-service
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  # Critical for service discovery

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.microservice: DEBUG

app:
  welcome-message: "Welcome to the Posts Service for Phumie"
  max-retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always